name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
        env:
          CYPRESS_AUTOMATED_TESTING_EMAIL: ${{secrets.CYPRESS_AUTOMATED_TESTING_EMAIL}}
          CYPRESS_AUTOMATED_TESTING_PASSWORD: ${{secrets.CYPRESS_AUTOMATED_TESTING_PASSWORD}}
          CYPRESS_AUTOMATED_TESTING_HOST_EMAIL: ${{secrets.CYPRESS_AUTOMATED_TESTING_HOST_EMAIL}}
          CYPRESS_AUTOMATED_TESTING_HOST_PASSWORD: ${{secrets.CYPRESS_AUTOMATED_TESTING_HOST_PASSWORD}}
          CYPRESS_AUTOMATED_TESTING_NO_NAME_EMAIL: ${{secrets.CYPRESS_AUTOMATED_TESTING_NO_NAME_EMAIL}}
          CYPRESS_AUTOMATED_TESTING_NO_NAME_PASSWORD: ${{secrets.CYPRESS_AUTOMATED_TESTING_NO_NAME_PASSWORD}}
          CYPRESS_AUTOMATED_TESTING_SUPABASE_URL: ${{secrets.CYPRESS_AUTOMATED_TESTING_SUPABASE_URL}}
          CYPRESS_AUTOMATED_TESTING_SUPABASE_ANON_KEY: ${{secrets.CYPRESS_AUTOMATED_TESTING_SUPABASE_ANON_KEY}}
