name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npx expo export -p web
          start: npm start
        env:
          CYPRESS_TEST_USER_EMAIL: ${{secrets.CYPRESS_TEST_USER_EMAIL}}
          CYPRESS_TEST_USER_PASSWORD: ${{secrets.CYPRESS_TEST_USER_PASSWORD}}
          CYPRESS_TEST_USER_ID: ${{secrets.CYPRESS_TEST_USER_ID}}
          CYPRESS_TEST_USER_NAME: ${{secrets.CYPRESS_TEST_USER_NAME}}
          CYPRESS_TEST_GAME_ID: ${{secrets.CYPRESS_TEST_GAME_ID}}
          CYPRESS_TEST_HOST_USER_ID: ${{secrets.CYPRESS_TEST_HOST_USER_ID}}
          CYPRESS_TEST_USER_ID_1: ${{secrets.CYPRESS_TEST_USER_ID_1}}
          CYPRESS_TEST_USER_ID_2: ${{secrets.CYPRESS_TEST_USER_ID_2}}
          CYPRESS_TEST_USER_ID_3: ${{secrets.CYPRESS_TEST_USER_ID_3}}
          CYPRESS_TEST_USER_ID_4: ${{secrets.CYPRESS_TEST_USER_ID_4}}
          CYPRESS_TEST_USER_ID_5: ${{secrets.CYPRESS_TEST_USER_ID_5}}
          CYPRESS_TEST_USER_ID_6: ${{secrets.CYPRESS_TEST_USER_ID_6}}
          CYPRESS_TEST_USER_ID_7: ${{secrets.CYPRESS_TEST_USER_ID_7}}
          CYPRESS_TEST_USER_ID_8: ${{secrets.CYPRESS_TEST_USER_ID_8}}
          CYPRESS_TEST_USER_ID_9: ${{secrets.CYPRESS_TEST_USER_ID_9}}
          CYPRESS_TEST_USER_ID_10: ${{secrets.CYPRESS_TEST_USER_ID_10}}
          CYPRESS_TEST_USER_ID_11: ${{secrets.CYPRESS_TEST_USER_ID_11}}
          CYPRESS_TEST_USER_ID_12: ${{secrets.CYPRESS_TEST_USER_ID_12}}
          CYPRESS_TEST_USER_ID_13: ${{secrets.CYPRESS_TEST_USER_ID_13}}
          CYPRESS_TEST_USER_ID_14: ${{secrets.CYPRESS_TEST_USER_ID_14}}
