name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: temp debugging - CYPRESS_AUTOMATED_TESTING_EMAIL
        run: echo ${{secrets.CYPRESS_AUTOMATED_TESTING_EMAIL}}
      - name: temp debugging - CYPRESS_AUTOMATED_TESTING_PASSWORD
        run: echo ${{secrets.CYPRESS_AUTOMATED_TESTING_PASSWORD}}
      - name: temp debugging - CYPRESS_AUTOMATED_TESTING_HOST_EMAIL
        run: echo ${{secrets.CYPRESS_AUTOMATED_TESTING_HOST_EMAIL}}
      - name: temp debugging - CYPRESS_AUTOMATED_TESTING_HOST_PASSWORD
        run: echo ${{secrets.CYPRESS_AUTOMATED_TESTING_HOST_PASSWORD}}
      - name: temp debugging - CYPRESS_AUTOMATED_TESTING_NO_NAME_EMAIL
        run: echo ${{secrets.CYPRESS_AUTOMATED_TESTING_NO_NAME_EMAIL}}
      - name: temp debugging - CYPRESS_AUTOMATED_TESTING_NO_NAME_PASSWORD
        run: echo ${{secrets.CYPRESS_AUTOMATED_TESTING_NO_NAME_PASSWORD}}
      # - name: Checkout
      #   uses: actions/checkout@v4
      # - name: Cypress run
      #   uses: cypress-io/github-action@v6
      #   with:
      #     build: npm run build
      #     start: npm start
      #   env:
      #     CYPRESS_AUTOMATED_TESTING_EMAIL: ${{secrets.CYPRESS_AUTOMATED_TESTING_EMAIL}}
      #     CYPRESS_AUTOMATED_TESTING_PASSWORD: ${{secrets.CYPRESS_AUTOMATED_TESTING_PASSWORD}}
      #     CYPRESS_AUTOMATED_TESTING_HOST_EMAIL: ${{secrets.CYPRESS_AUTOMATED_TESTING_HOST_EMAIL}}
      #     CYPRESS_AUTOMATED_TESTING_HOST_PASSWORD: ${{secrets.CYPRESS_AUTOMATED_TESTING_HOST_PASSWORD}}
      #     CYPRESS_AUTOMATED_TESTING_NO_NAME_EMAIL: ${{secrets.CYPRESS_AUTOMATED_TESTING_NO_NAME_EMAIL}}
      #     CYPRESS_AUTOMATED_TESTING_NO_NAME_PASSWORD: ${{secrets.CYPRESS_AUTOMATED_TESTING_NO_NAME_PASSWORD}}
      #     EXPO_PUBLIC_SUPABASE_URL: ${{vars.EXPO_PUBLIC_SUPABASE_URL}}
      #     EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{vars.EXPO_PUBLIC_SUPABASE_ANON_KEY}}
