name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npx expo export -p web
          start: npx serve dist -l 8081
        env:
          CYPRESS_TEST_USER_EMAIL: ${{secrets.CYPRESS_TEST_USER_EMAIL}}
          CYPRESS_TEST_USER_PASSWORD: ${{secrets.CYPRESS_TEST_USER_PASSWORD}}
          CYPRESS_TEST_USER_ID: ${{secrets.CYPRESS_TEST_USER_ID}}
          CYPRESS_TEST_GAME_ID: ${{secrets.CYPRESS_TEST_GAME_ID}}
          CYPRESS_TEST_15_PLAYER_GAME_ID: ${{secrets.CYPRESS_TEST_15_PLAYER_GAME_ID}}
          CYPRESS_TEST_ALREADY_STARTED_GAME_ID: ${{secrets.CYPRESS_TEST_ALREADY_STARTED_GAME_ID}}
          CYPRESS_TEST_ALREADY_JOINED_GAME_ID: ${{secrets.CYPRESS_TEST_ALREADY_JOINED_GAME_ID}}
          CYPRESS_TEST_HOST_GAME_ID: ${{secrets.CYPRESS_TEST_HOST_GAME_ID}}
          EXPO_PUBLIC_TEST_USER_EMAIL: ${{secrets.EXPO_PUBLIC_TEST_USER_EMAIL}}
          EXPO_PUBLIC_TEST_USER_PASSWORD: ${{secrets.EXPO_PUBLIC_TEST_USER_PASSWORD}}
          EXPO_PUBLIC_TEST_USER_ID: ${{secrets.EXPO_PUBLIC_TEST_USER_ID}}
